### ISSUE TITLE
New version for 2.3.1?

### ISSUE THREAD

**Issue by danielschonfeld** [fabric8io/elasticsearch-cloud-kubernetes#34]
Can an updated config file be made for ES 2.3.1?

**Comment by jimmidyson** [comment]
Of course - PR appreciated if possible.

**Comment by haizaar** [comment]
+1 for this.

**Comment by ddyycao** [comment]
+1

**Comment by mrmiroslav** [comment]
+1

**Comment by jimmidyson** [comment]
Please stop +1ing - using [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) is much better now it's been introduced.

As I said above, if anyone wants to submit a PR for this it's a good one to contribute to, especially if you've never sent in a PR before. Otherwise I'll try to get to it some time this week.

**Comment by jimmidyson** [comment]
Thanks to @pires - released to Maven Central - http://repo1.maven.org/maven2/io/fabric8/elasticsearch-cloud-kubernetes/2.3.1/.
